apiVersion: v1
kind: Service
metadata:
  name: analyticslb
  labels:
    app: analytics-api
spec:
  type: LoadBalancer
  selector:
    app: analytics-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5153